### ISSUE TITLE
[Question] enable AMDGPU precise memory access reporting 

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm-Developer-Tools/ROCgdb#17]
I have two questions. How can a user enable the AMDGPU precise memory access reporting ? Could it be enabled by default ?  Thanks.

```
Warning: precise memory violation signal reporting is not enabled, reported
location may not be accurate.  See "show amdgpu precise-memory".

(gdb) show amdgpu precise-memory
AMDGPU precise memory access reporting is off (currently disabled).
```

**Comment by t-tye** [comment]
You can use the "set amdgpu precise-memory on" command. See section "22.4.10.13 AMD GPU Memory Violation Reporting" in the ROCgdb User Manual at https://docs.amd.com/bundle/ROCDebugger-User-Guide-v5.3/page/AMD-GPU.html .

It is not enabled by default as it can affect performance. But you could enable it in your gdbinit startup file.

**Comment by zjin-lcf** [comment]
Thank you for your explanation and link.
