### ISSUE TITLE
Does ROCgdb can debug the kernel code of hip?

### ISSUE THREAD

**Issue by andyzhanged** [ROCm-Developer-Tools/ROCgdb#4]
The kernel code will run on GPU, So ROCgdb is developed to debug kernel code?
thanks.

**Comment by t-tye** [comment]
ROCgdb is a heterogeneous debugger so will allow debugging of both the host CPU and device GPU in a unified manner. See the README-ROCm.md and updated Gdb User Manual that comes with it.
